// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { Counter } from "./src/index";

declare global {
  interface Env {
    COUNTER: __TelnyxActorNamespace<Counter>;
    SUPPORT_CONFIG: __TelnyxKvNamespace;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    COUNTER: __TelnyxActorNamespace<Counter>;
    SUPPORT_CONFIG: __TelnyxKvNamespace;
  }
}

export {};
