// Shared data contracts and validation helpers for the Telnyx developer
// support assistant.
//
// This module defines the pure, dependency-free shapes used across the Edge
// Function: the ticket model stored in the caller's Actor, the dynamic
// variables written by the /init webhook (and the subset the tool is allowed
// to write back), the request/response of the create-ticket webhook, the FAQ
// topic used by the MCP server, and a set of business limits.
//
// Keeping the contracts here lets every handler, the Actor implementation
// (step 5), the MCP server (step 7), and the deployment script share the same
// definitions, which avoids drift between the backend and the assistant.

// ---------------------------------------------------------------------------
// Business limits
// ---------------------------------------------------------------------------

// Maximum length of a ticket subject. Enforced in validateSubject.
export const MAX_SUBJECT_LENGTH = 100;

// Maximum length of a ticket description. Enforced in validateDescription.
export const MAX_DESCRIPTION_LENGTH = 1500;

// Word-count limits for an FAQ long answer. Range enforced when the FAQ
// catalogue is authored (see faq.ts in step 7).
export const MIN_FAQ_LONG_ANSWER_WORDS = 80;
export const MAX_FAQ_LONG_ANSWER_WORDS = 120;

// Maximum number of recent tickets presented verbally by the assistant on
// initialization. Older tickets remain in Actor storage but are not read out.
export const PRESENTABLE_TICKETS_LIMIT = 3;

// Tickets updated within this window (in days) are considered "recent" and
// may be presented, alongside all "open" tickets regardless of age.
export const RECENT_TICKET_WINDOW_DAYS = 30;

// Maximum length of an operation_id, used only as a sanity guard against
// abusive preset values. operation_id is generated from the call context
// and dedupes repeated webhook deliveries.
export const MAX_OPERATION_ID_LENGTH = 128;

// ---------------------------------------------------------------------------
// Ticket model (persisted in the caller's Actor)
// ---------------------------------------------------------------------------

// Lifecycle of a support ticket. A new ticket always starts as "open".
// "in_progress" indicates a technician has picked it up; "resolved" closes it.
export type TicketStatus = "open" | "in_progress" | "resolved";

// A single support ticket, stored in the caller's Actor state. Dates are
// ISO-8601 strings to remain JSON-serializable through Actor storage.
export interface Ticket {
  // UUIDv4 generated by the Actor on creation.
  id: string;
  // Short, human-readable reference, unique within this caller's tickets.
  // Generated by the Actor from next_ticket_number (e.g. "T-0007").
  reference: string;
  // Caller-provided subject, validated to <= MAX_SUBJECT_LENGTH characters.
  subject: string;
  // Caller-provided description, validated to <= MAX_DESCRIPTION_LENGTH.
  description: string;
  // Current lifecycle status.
  status: TicketStatus;
  // Short, voice-friendly summary of the current status, written by the
  // caller's Actor (e.g. "Awaiting handling."). Read aloud by the assistant.
  status_summary: string;
  // ISO-8601 creation timestamp.
  created_at: string;
  // ISO-8601 last-update timestamp.
  updated_at: string;
  // Deduplication key. Two create-ticket webhooks with the same operation_id
  // return the same ticket. Prevents retries from creating duplicates.
  operation_id: string;
}

// Persistent state of one caller's Actor. Stored under a single key in
// this.ctx.storage. The next_ticket_number counter guarantees unique
// references even when the ticket list grows.
export interface ActorState {
  // Next reference number assigned by createTicket. Monotonic.
  next_ticket_number: number;
  // All tickets for this caller, in insertion order. Historical fixtures may
  // have older dates; the init handler sorts and selects the voice subset.
  tickets: Ticket[];
}

// The status_summary assigned to a brand-new ticket.
export const NEW_TICKET_STATUS_SUMMARY = "Awaiting handling.";

// Business input for one actor creation. Caller identity is resolved by the
// Function before RPC; no phone number belongs in this actor input or state.
export interface CreateTicketInput {
  subject: string;
  description: string;
  operation_id: string;
}

// Minimal creation result. A repeated operation returns these same identifiers.
export type CreateTicketResult = Pick<Ticket, "id" | "reference">;

// Demo-only input. The actor assigns ids and references itself, while fixtures
// may supply documented statuses and historical timestamps for a voice demo.
// A stable operation_id identifies a fixture across repeated seed calls.
export interface DemoTicketInput extends CreateTicketInput {
  status: TicketStatus;
  status_summary: string;
  created_at: string;
  updated_at: string;
}

// Explicit batch wrapper used by the preparation-only actor method.
export interface SeedDemoTicketsInput {
  tickets: DemoTicketInput[];
}

// Number of new fixtures inserted; existing operation ids are left untouched.
export interface SeedDemoTicketsResult {
  added_count: number;
}

// ---------------------------------------------------------------------------
// Dynamic variables exchanged with the AI Assistant
// ---------------------------------------------------------------------------

// Keys written by the POST /init webhook. These shape the conversation from
// the very first node; defaults are used when /init cannot be reached.
export const INIT_DYNAMIC_VARIABLE_KEYS = [
  "init_ok",
  "can_create_ticket",
  "tickets_count",
  "tickets_json",
  "technician_available",
  "greeting_text",
  "operation_id",
] as const;
export type InitDynamicVariableKey = (typeof INIT_DYNAMIC_VARIABLE_KEYS)[number];

// Keys the SET_SUPPORT_VARIABLES shared tool may write back mid-conversation.
// This list is the source of truth for the allowlist enforced in step 8;
// identity, flags, and creation identifiers must never be writable from here.
export const WRITABLE_DYNAMIC_VARIABLE_KEYS = [
  "selected_ticket_status_text",
  "faq_topic_id",
  "faq_long_text",
  "ticket_subject",
  "ticket_description",
] as const;
export type WritableDynamicVariableKey = (typeof WRITABLE_DYNAMIC_VARIABLE_KEYS)[number];

// Keys populated from the create-ticket webhook response, stored as variables
// so the TICKET_CREATED Speak node can announce the reference.
export const CREATED_TICKET_VARIABLE_KEYS = [
  "created_ticket_id",
  "created_ticket_reference",
] as const;
export type CreatedTicketVariableKey = (typeof CREATED_TICKET_VARIABLE_KEYS)[number];

// Shape of the /init response's dynamic_variables object. Every field is a
// JSON primitive (or a JSON-encoded string for the ticket list) because the
// assistant interpolates them as strings.
export interface InitDynamicVariables {
  // True when /init completed all steps without an unrecoverable error.
  init_ok: boolean;
  // True when the backend is ready to accept a new ticket. False whenever a
  // hard dependency (Actor, KV) is unavailable, so the caller is never sent
  // into a ticket-intake branch that cannot succeed.
  can_create_ticket: boolean;
  // Number of tickets actually presented in tickets_json (<= PRESENTABLE_TICKETS_LIMIT).
  tickets_count: number;
  // JSON-encoded array of presentable tickets (id, reference, subject,
  // status, status_summary, updated_at). Kept as a string for safe transport.
  tickets_json: string;
  // Value of the technician_available feature flag read from KV.
  technician_available: boolean;
  // Greeting text spoken by the greeting Speak node. Personalized when
  // tickets exist, generic otherwise.
  greeting_text: string;
  // Opaque key tying this call's ticket creation to a single idempotent Actor
  // operation. Generated from the stable call context in step 6.
  operation_id: string;
}

// Fallback values used when /init fails or is unreachable. They are also the
// assistant's configured defaults, so the conversation degrades gracefully:
// the caller is never told their records are empty when they may not be, and
// the technician offer is disabled until KV confirms the flag.
export const DEFAULT_INIT_DYNAMIC_VARIABLES: InitDynamicVariables = {
  init_ok: false,
  can_create_ticket: false,
  tickets_count: 0,
  tickets_json: "[]",
  technician_available: false,
  greeting_text:
    "Hello, this is the Telnyx developer support line. How can I help you today?",
  operation_id: "",
};

// Subset of a Ticket exposed in tickets_json, after pruning fields that must
// not leak into the assistant's context (e.g. operation_id, description,
// caller phone). The assistant reads subject/status/summary aloud only.
export interface PresentableTicket {
  id: string;
  reference: string;
  subject: string;
  status: TicketStatus;
  status_summary: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Create-ticket webhook contract (POST /tickets/create)
// ---------------------------------------------------------------------------

// Body sent by the CREATE_TICKET shared tool. ticket_subject and
// ticket_description come from the model's collected values; caller_phone and
// operation_id come from preset body fields configured on the tool, so the
// model cannot choose or forge them.
export interface CreateTicketRequest {
  ticket_subject: string;
  ticket_description: string;
  caller_phone: string;
  operation_id: string;
}

// Success response (HTTP 200). The stored identifiers are mirrored into the
// conversation as variables by the tool's store_fields_as_variables config.
export interface CreateTicketResponse {
  ticket_id: string;
  ticket_reference: string;
}

// ---------------------------------------------------------------------------
// FAQ topic (served by the MCP server in step 7)
// ---------------------------------------------------------------------------

// One entry in the documentation catalogue exposed through MCP tools. Topics
// are authored in faq.ts and are intentionally few, verified, and stable.
export interface FaqTopic {
  // Stable identifier used by the read_short_answer and read_long_answer tools.
  id: string;
  // Documentation page title. The assistant announces this verbatim.
  title: string;
  // Short description of what the page covers, used by the model to decide
  // whether a caller question is on-topic. Never read aloud.
  coverage: string;
  // Canonical documentation URL. Returned to the model but never spoken.
  documentation_url: string;
  // 80-120 word explanation suitable for voice delivery, returned by
  // read_long_answer.
  long_answer: string;
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

// Result shape returned by the text validators. We use a discriminated
// union so callers can branch on `ok` without further checks.
export type ValidationResult =
  | { ok: true; value: string }
  | { ok: false; error: string };

// Validate a ticket subject: required, trimmed, <= MAX_SUBJECT_LENGTH.
// Returns the trimmed value on success or a short, sanitized error message.
// Rejects non-string inputs (number, object, array, boolean) cleanly instead
// of throwing: a bad JSON payload must not crash the handler.
export function validateSubject(input: string | null | undefined): ValidationResult {
  if (typeof input !== "string") {
    return { ok: false, error: "subject must be a string" };
  }
  const trimmed = input.trim();
  if (trimmed.length === 0) {
    return { ok: false, error: "subject is required" };
  }
  if (trimmed.length > MAX_SUBJECT_LENGTH) {
    return { ok: false, error: `subject exceeds ${MAX_SUBJECT_LENGTH} characters` };
  }
  return { ok: true, value: trimmed };
}

// Validate a ticket description: required, trimmed, <= MAX_DESCRIPTION_LENGTH.
// Rejects non-string inputs cleanly; never throws.
export function validateDescription(input: string | null | undefined): ValidationResult {
  if (typeof input !== "string") {
    return { ok: false, error: "description must be a string" };
  }
  const trimmed = input.trim();
  if (trimmed.length === 0) {
    return { ok: false, error: "description is required" };
  }
  if (trimmed.length > MAX_DESCRIPTION_LENGTH) {
    return { ok: false, error: `description exceeds ${MAX_DESCRIPTION_LENGTH} characters` };
  }
  return { ok: true, value: trimmed };
}

// Validate an operation_id: required, non-empty, <= MAX_OPERATION_ID_LENGTH.
// operation_id is not user-facing; this guard avoids an attacker-supplied
// huge value reaching the Actor. Rejects non-string inputs cleanly.
export function validateOperationId(
  input: string | null | undefined,
): ValidationResult {
  if (typeof input !== "string") {
    return { ok: false, error: "operation_id must be a string" };
  }
  const trimmed = input.trim();
  if (trimmed.length === 0) {
    return { ok: false, error: "operation_id is required" };
  }
  if (trimmed.length > MAX_OPERATION_ID_LENGTH) {
    return { ok: false, error: "operation_id is too long" };
  }
  return { ok: true, value: trimmed };
}

// True when value is a real ISO-8601 date-time in the expected shape and a
// valid calendar date and time. We do NOT rely on Date.parse for validity,
// because it silently normalizes impossible dates such as 2026-02-31 to
// 2026-03-03 and would return a finite timestamp. Instead we extract the
// components with a strict regex and validate them against the proleptic
// Gregorian calendar, including leap-year rules. Used to validate dates
// coming from JSON (Actor storage) before trusting them in presentable tickets.
export function isValidIsoDate(value: string | null | undefined): boolean {
  if (typeof value !== "string" || value.length === 0) return false;

  // Strict shape: YYYY-MM-DDTHH:mm(:ss)?(.sss)?(Z or +HH:mm or -HH:mm).
  // Captures everything; no normalization is applied by the regex itself.
  const m =
    /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?(?:\.(\d{1,3}))?(Z|[+-]\d{2}:\d{2})$/.exec(
      value,
    );
  if (!m) return false;

  const year = Number(m[1]);
  const month = Number(m[2]);
  const day = Number(m[3]);
  const hour = Number(m[4]);
  const minute = Number(m[5]);
  const second = m[6] !== undefined ? Number(m[6]) : 0;
  // Fractional seconds are accepted for shape but not validated further; they
  // don't affect calendar validity, only sub-second precision.

  if (!isValidCalendarDate(year, month, day)) return false;
  if (!isValidTimeOfDay(hour, minute, second)) return false;

  // Final sanity: Date.parse must produce a finite timestamp. This catches
  // timezone offsets outside ±24:00 that the regex shape alone permits.
  const parsed = Date.parse(value);
  return Number.isFinite(parsed);
}

// Validate a (year, month, day) triple against the Gregorian calendar, with
// the correct leap-year rule. month is 1-12; day is 1-31. Returns false for
// impossible dates: February 30/31, April 31, month 13, day 0, etc.
export function isValidCalendarDate(
  year: number,
  month: number,
  day: number,
): boolean {
  if (!Number.isInteger(year) || !Number.isInteger(month) || !Number.isInteger(day)) {
    return false;
  }
  if (month < 1 || month > 12) return false;
  if (day < 1) return false;

  // Days in each month for a common (non-leap) year.
  const daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

  // Leap-year rule: divisible by 4, excluding centennial years not divisible
  // by 400. Applied to February only.
  const isLeap =
    (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
  const febDays = isLeap ? 29 : 28;

  const maxDay = month === 2 ? febDays : daysInMonth[month - 1];
  return day <= maxDay;
}

// Validate an (hour, minute, second) triple. hour is 0-23, minute and second
// are 0-59. We must not allow hour 24 (Date.parse would wrap it to the next
// day) — that would defeat the purpose of calendar-aware validation.
export function isValidTimeOfDay(
  hour: number,
  minute: number,
  second: number,
): boolean {
  if (!Number.isInteger(hour) || !Number.isInteger(minute) || !Number.isInteger(second)) {
    return false;
  }
  return (
    hour >= 0 && hour <= 23 && minute >= 0 && minute <= 59 && second >= 0 && second <= 59
  );
}

// Count words in a long answer, used to keep FAQ entries inside the voice
// budget (MIN..MAX_FAQ_LONG_ANSWER_WORDS).
export function countWords(text: string | null | undefined): number {
  const trimmed = (text ?? "").trim();
  if (trimmed.length === 0) return 0;
  // Split on whitespace runs; avoids miscounting empty strings.
  return trimmed.split(/\s+/).length;
}
